spring:
  application:
    name: flink-traffic-service
  profiles:
    active: local

#management:
#  health:
#    db:
#      enabled: false
#    redis:
#      enabled: false
#    elasticsearch:
#      enabled: false